/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomePage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedOutfit` | `/SavedOutfit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedPage` | `/SavedPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Wardrobe` | `/Wardrobe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/WelcomePage` | `/WelcomePage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/WelcomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SavedOutfit` | `/SavedOutfit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SavedPage` | `/SavedPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Wardrobe` | `/Wardrobe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/WelcomePage` | `/WelcomePage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/WelcomePage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SavedOutfit${`?${string}` | `#${string}` | ''}` | `/SavedOutfit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SavedPage${`?${string}` | `#${string}` | ''}` | `/SavedPage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Wardrobe${`?${string}` | `#${string}` | ''}` | `/Wardrobe${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/WelcomePage${`?${string}` | `#${string}` | ''}` | `/WelcomePage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomePage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedOutfit` | `/SavedOutfit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedPage` | `/SavedPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Wardrobe` | `/Wardrobe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/WelcomePage` | `/WelcomePage`; params?: Router.UnknownInputParams; };
    }
  }
}
